# Generated by Django 4.2.4 on 2023-09-26 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_customuser_password_alter_customuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipamentosComentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentariosEquipamentos', to='main.comentarios')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamentosComentarios', to='main.equipamentos')),
            ],
        ),
    ]
