# Generated by Django 4.2.4 on 2023-09-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_equipamentoscomentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamentos',
            name='image',
            field=models.CharField(max_length=2000000),
        ),
    ]
