# Generated by Django 4.2.4 on 2023-09-26 06:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_equipamentos_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
