# Generated by Django 4.2.4 on 2023-09-30 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_comentarios_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamentos',
            name='comentarios',
            field=models.ManyToManyField(null=True, related_name='equipamentos', to='main.comentarios'),
        ),
    ]
